import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material";

import theme from "../theme";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "By Alex",
  description: "Generated by create next app",
};

const style = {
  margin: "0",
  backgroundColor: "#0A0908",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body style={style}>
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
